// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"app-go/service"
	"context"
	"sync"
)

// Ensure, that AppMock does implement service.App.
// If this is not the case, regenerate this file with moq.
var _ service.App = &AppMock{}

// AppMock is a mock implementation of service.App.
//
//	func TestSomethingThatUsesApp(t *testing.T) {
//
//		// make and configure a mocked service.App
//		mockedApp := &AppMock{
//			ReadFunc: func(ctx context.Context, query string) (string, error) {
//				panic("mock out the Read method")
//			},
//			SomethingFunc: func(ctx context.Context, str string) (string, error) {
//				panic("mock out the Something method")
//			},
//			SomethingIdFunc: func(ctx context.Context, str string, id string) (string, error) {
//				panic("mock out the SomethingId method")
//			},
//		}
//
//		// use mockedApp in code that requires service.App
//		// and then make assertions.
//
//	}
type AppMock struct {
	// ReadFunc mocks the Read method.
	ReadFunc func(ctx context.Context, query string) (string, error)

	// SomethingFunc mocks the Something method.
	SomethingFunc func(ctx context.Context, str string) (string, error)

	// SomethingIdFunc mocks the SomethingId method.
	SomethingIdFunc func(ctx context.Context, str string, id string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Read holds details about calls to the Read method.
		Read []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Query is the query argument value.
			Query string
		}
		// Something holds details about calls to the Something method.
		Something []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Str is the str argument value.
			Str string
		}
		// SomethingId holds details about calls to the SomethingId method.
		SomethingId []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Str is the str argument value.
			Str string
			// ID is the id argument value.
			ID string
		}
	}
	lockRead        sync.RWMutex
	lockSomething   sync.RWMutex
	lockSomethingId sync.RWMutex
}

// Read calls ReadFunc.
func (mock *AppMock) Read(ctx context.Context, query string) (string, error) {
	if mock.ReadFunc == nil {
		panic("AppMock.ReadFunc: method is nil but App.Read was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Query string
	}{
		Ctx:   ctx,
		Query: query,
	}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc(ctx, query)
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//
//	len(mockedApp.ReadCalls())
func (mock *AppMock) ReadCalls() []struct {
	Ctx   context.Context
	Query string
} {
	var calls []struct {
		Ctx   context.Context
		Query string
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// Something calls SomethingFunc.
func (mock *AppMock) Something(ctx context.Context, str string) (string, error) {
	if mock.SomethingFunc == nil {
		panic("AppMock.SomethingFunc: method is nil but App.Something was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Str string
	}{
		Ctx: ctx,
		Str: str,
	}
	mock.lockSomething.Lock()
	mock.calls.Something = append(mock.calls.Something, callInfo)
	mock.lockSomething.Unlock()
	return mock.SomethingFunc(ctx, str)
}

// SomethingCalls gets all the calls that were made to Something.
// Check the length with:
//
//	len(mockedApp.SomethingCalls())
func (mock *AppMock) SomethingCalls() []struct {
	Ctx context.Context
	Str string
} {
	var calls []struct {
		Ctx context.Context
		Str string
	}
	mock.lockSomething.RLock()
	calls = mock.calls.Something
	mock.lockSomething.RUnlock()
	return calls
}

// SomethingId calls SomethingIdFunc.
func (mock *AppMock) SomethingId(ctx context.Context, str string, id string) (string, error) {
	if mock.SomethingIdFunc == nil {
		panic("AppMock.SomethingIdFunc: method is nil but App.SomethingId was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Str string
		ID  string
	}{
		Ctx: ctx,
		Str: str,
		ID:  id,
	}
	mock.lockSomethingId.Lock()
	mock.calls.SomethingId = append(mock.calls.SomethingId, callInfo)
	mock.lockSomethingId.Unlock()
	return mock.SomethingIdFunc(ctx, str, id)
}

// SomethingIdCalls gets all the calls that were made to SomethingId.
// Check the length with:
//
//	len(mockedApp.SomethingIdCalls())
func (mock *AppMock) SomethingIdCalls() []struct {
	Ctx context.Context
	Str string
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		Str string
		ID  string
	}
	mock.lockSomethingId.RLock()
	calls = mock.calls.SomethingId
	mock.lockSomethingId.RUnlock()
	return calls
}
